export type PokemonType = {
    normal: "normal",
    fire: "fire",
    fighting: "fighting",
    water: "water",
    flying: "flying",
    grass: "grass",
    poison: "poison",
    electric: "electric",
    ground: "ground",
    psychic: "psychic",
    rock: "rock",
    ice: "ice",
    bug: "bug",
    dragon: "dragon",
    ghost: "ghost",
    dark: "dark",
    steel: "steel",
    fairy: "fairy",
};